canonical/documentation-style-guide

- README.md
- en/index.md
- en/metadata.yaml
Issue:
- Headings in side navigation do not reflect actual page structure
Solution:
- Updated `en/metadata.yaml` with current heading structure
- Changed heading level of "Code examples in documentation"
**Note:** Slightly reworded README.md instructions for `documentation-builder` because they confused me a bit.
> Fixed sidebar navigation

- en/index.md
I got this as a reference from 
@k-dimple in https://github.com/canonical/open-documentation-academy/issues/26#issue-2175647666 
and noticed one of the comments showing up in the preview:
this should fix it.
> fix rule comment

- getting-started.md
Link to "existing rules" was outdated. Updated link to new anchor.
> Small anchor fix

- styles/Canonical/000-Repeated-words.yml
Call out when two successively repeated words are used (e.g. "I went to the the store."). This happens very often and it's hard to catch since the words are fine in themselves.
This rule is not implementing the Canonical style guide. It is identifying a syntactical error. Because of this, I chose the numbering scheme of '000-Some-rule'. If we agree to this format for outright mistakes, I can make an addition to the README explaining it.
> Identify repeated words

- styles/Canonical/011-Headings-not-followed-by-heading.yml
- test/test011.md
- test/test011.rst
Hi @evilnick ,
This PR is for DOCPR-381.
I did make some changes w.r.t. the definition of this rule.
Headings of the same level can follow each other (e.g. H1 > H2 > H2) as long as there is intervening text in between.
So this rule checks for stacked headings (with no content under the heading) regardless if the consecutive headings are of the same level, or different levels. This would also help detect errors if headings are unintentionally defined in the source files but not expanded on.
I've added 2 test files with minimal test cases that should trigger errors for this rule.
Thanks!
> DOCPR-381: Vale rule no. 11 no stacked headings

- styles/Canonical/001-English-words-spelling-suggestions.yml
- test/test001.md
Hi @evilnick , @SecondSkoll ,
This PR is for DOCPR-371.
This rule is focused only on making suggestions for words using US spelling, to UK English spelling.
Style guide section: https://docs.ubuntu.com/styleguide/en/#spelling
~~I think it'll be better to create separate rules for common technology terms we want to standardise, e.g. "website" and not "web site". That would be cleaner to maintain and test.~~
[Update: I just realised this is indeed a separate rule in the style guide source itself.]
I also think it would be good to start following a proper naming convention for the test files we include.
E.g. for rule no. 011, the test file name would be test011.md or test011.rst, so we know which rules are expected to fail.
Thanks!
> DOCPR-371: Vale rule no. 01 British English check

- styles/Canonical/004-Canonical-product-names.yml
- test/test004.md
Canonical product name, implemented as suggestions for replacement from common errors.
> Add rule 004

- en/index.md
- styles/Canonical/003-Ubuntu-names-versions.yml
- test/test003.md
PR for DOCPR-373 to address rule no. 003, correct use of Ubuntu versions.
I don't have examples of what are common incorrect uses; hence am just making assumptions about the incorrect scenarios.
The list of releases are checked until 18.04 since the rest are historically very old versions already. This is due to the current regex definition which is not too flexible in terms of versions that are being detected (to be more accurate).
Also there is only 1 version of the test file (in MD) since for this rule, the syntax for RST vs MD is irrelevant.
Thanks.
> DOCPR-373: rule no. 003 correct use of Ubuntu versions

- styles/Canonical/014a-Numbers-greater-than-nine-should-be-in-numeric-form.yml
- styles/Canonical/014b-Numbers-with-five-or-more-digits-must-have-comma-separators.yml
- styles/Canonical/014b-Numbers-with-four-or-more-digits-must-have-comma-separators.yml
- test/test14.md
@evilnick @SecondSkoll 
This is for [DOCPR-384](https://warthogs.atlassian.net/browse/DOCPR-384).
This rule was a bit more complicated than I expected and I had to break it down into two sub-rules:
- Numbers greater than nine should not be spelled out
- Numbers greater than 999 should have appropriate comma separators
It also got extremely complicated (or the rule being too long) when I tried to match all numbers greater than nine, so I have tried a simpler way. Hope this is fine!
[DOCPR-384]: https://warthogs.atlassian.net/browse/DOCPR-384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Vale rule 14: Numeric format for numbers above nine and for numbers greater than 9999

- styles/Canonical/016-No-inline-comments.yml
- test/test016.md
- test/test016.rst
Adds a rule that raises a warning every time it detects a code block (defined by ``` in MD and `code-block` in reST) and that contains a line with a codeblock (`#` and `//` as of now as the two popular ways to define a comment in many languages, the list can be expanded).
The rule will raise a false positive if `#` or `\\` that is not a comment occurs in the code block. The only example I can think of is Win path format e.g. `C:\\`. :thinking:
> Avoid inlining comments in code blocks

- styles/config/vocabularies/Canonical/Accept.txt
- test/testvocab.md
- vale.ini
Adding a Canonical vocabulary that can be iteratively updated.
@evilnick I am a little blocked on this - when running testing on the test file, the capitalization rule is still triggered on the headings even though `Accept.txt` should work as a list of exceptions for any style rules. Am I missing something? Could you point me in the right direction? :thinking:
> Add Canonical vocabulary

- en/index.md
- en/metadata.yaml
PR for [Jira ticket DOCPR-663](https://warthogs.atlassian.net/browse/DOCPR-663), which aims to include a brief reference to Diátaxis in the style guide.
Diátaxis is the foundation from which much of Canonical's product documentation is built. The form and style of a page of documentation is influenced by the Diátaxis category in which it fits.
Given its centrality, a reader might expect to find a reference to this framework in the style guide.
This PR adds a brief section on Diátaxis to the top of the style guide. It mentions briefly:
- That Diátaxis should be used
- The four categories in Diátaxis
- How the categories can influence style
- A link to a more detailed resource (the Diátaxis website)
> DOCPR-663: add section on Diátaxis to the style guide

- en/metadata.yaml
This is a tiny fix to the anchor link generated for the Diátaxis section of the style guide.
Currently the `href` is `#diataxis`, which does not navigate to the section when clicked.
When changed to `#diátaxis` in the browser inspector the anchor link enables navigation as expected.
This PR changes the relevant location value in the `metadata.yaml`.
> fix: diataxis anchor link

- en/metadata.yaml
A [previous PR](https://github.com/canonical/praecepta/pull/47) attempted a naive fix for the problem of a non-functional  internal link to the new Diátaxis section, where an attempt was made to include the accented character in the url. This did not work.
In this PR, the accented character is replaced by a url-encoded version, with `á` replaced by `%C3%A1`. The resultant url worked during local testing but we need to check after the site is built.
If this fix doesn't work we might need to consider a simplified version of the section header itself or, alternatively, look into how the `metadata.yaml` is parsed.
> fix: use url-encoding for diataxis

- styles/config/vocabularies/Canonical/Accept.txt
Added the word "Charmhub" (referring to [charmhub.io](https://charmhub.io/)) as an exception to Vale style checks.
> Added 'Charmhub' to Accept.txt

- styles/Canonical/004-Canonical-product-names.yml
Fix https://github.com/canonical/praecepta/issues/56
Fix the issue by adjusting the message: swap the parameters for the correct version first and the original second.
Make the message shorter for it to fit into a single line of output for shorter words.
> Update message in rule 4

- styles/Canonical/006-Contractions-forbidden.yml
For some reason, people often use backticks instead of apostrophes in contractions. I added them to the rule.
> Add Backticks to 006-Contractions-forbidden.yml

- styles/Canonical/015-No-prompts-in-comments.yml
- test/test015.md
- test/test015.rst
Implement the Rule # 15: No prompts in code blocks 
After multiple attempts to make it work with sophisticated RegEx (that matched every code block first) I've reduced the regex to detect the specific symbols used for CLI prompts used at the very beginning of a line.
That solution works great for its simple implementation: it gets the job done with no false positives detected so far.
> Rule15: Prompts in codeblocks

- en/index.md
- en/metadata.yaml
PR for Jira ticket DOCPR-664, which aims to include a brief reference to Video in the style guide.
Videos are occasionally included in our documentation and are used prominently as a means of documentation elsewhere, so we should offer some guidance.
This proposal briefly refers to some of the difficulties of including videos, without going into their many complexities.
It also attempts to reflect some best practice that is currently implemented at Canonical, such as text-based video, and reiterates that if video is used as a form of documentation then it should meet certain standards.
> DOCPR-664: add section on video to style guide

- en/index.md
Add some futrher text advising on the use of placeholders in text.
This doesn't need to be added to navigation as it is a subset of the Code section.
> Add placeholder advice

- README.md
- vale.ini
This PR:
- adds a low-noise default config, which explicitly sets each of the rules
- adds a section to the readme to explain this.
The rationale here is that we can use these defaults for a low-effort action anyone can use. This will not generate too much noise and cause them to turn it off, hopefully.
It also gives them an easy route to customise their config, because it is more evident what's going on.
We can update the config to target more rules when they give fewer false positives. The main impediment here is that we really need a very good/extensive accept.txt file that is likely to give good coverage for all products.
> add itemised config

- styles/Canonical/003-Ubuntu-names-versions.yml
- styles/Canonical/004-Canonical-product-names.yml
- styles/Canonical/005-Industry-product-names.yml
- styles/Canonical/007-Headings-sentence-case.yml
- styles/Canonical/011-Headings-not-followed-by-heading.yml
change three rules to error (blocking git actions) where legal and trademark issues may ensue; changed one rule to error where corporate communication standards would be violated; downgraded one rule (empty headings) to warning, since it is occasionally appropriate to do this.  this should represent the minimum blocking set we should require.
> set four rules to error, and moved one from error to warning

- styles/Canonical/003-Ubuntu-names-versions.yml
LTS version names are so far predictable, so we can just error or accept versions happening on even years followed by 04 LTS, without maintaining a full list
> ubuntu-names-versions: Simplify LTS matching regexes

- en/index.md
The index page still recommends the UK "virtualisation" spelling. I'm updating it to the US "virtualization" spelling that we're using now.
> New US spelling: virtualisation → virtualization

- styles/Canonical/017-Avoid-long-code-blocks.yml
@rkratky found some strangeness with the Subiquity docs that caused Vale to hang. I narrowed it down to a specific document hanging on rule 17. Issue came about from the code block having many spaces in a line with text, this was caused by a backtracking error due to the nested, insufficiently bound quantifiers.
This does mean that some parameters may be caught as code block lines, but it does fix the main issue for now.
> fix: rule 17 catastrophic backtracking

- vale.ini
I briefly considered adding this machinery to the spelling rule in `000-US-spellcheck.yml` but quickly realized I don't know a good way to do that.
> add reST-only ignore list for spelling checks

- styles/Canonical/000-US-spellcheck.yml
- styles/Canonical/001-English-words-spelling-suggestions.yml
- styles/Canonical/003-Ubuntu-names-versions.yml
- styles/Canonical/004-Canonical-product-names.yml
- styles/Canonical/005-Industry-product-names.yml
- styles/Canonical/006-Contractions-forbidden.yml
- styles/Canonical/010-Punctuation-double-spaces.yml
- styles/Canonical/020-Cliche-words-and-phrases.yml
- styles/Canonical/025a-latinisms-with-english-equivalents.yml
- styles/Canonical/025b-latinisms-to-reconsider.yml
- styles/Canonical/025c-latinisms-to-avoid.yml
- styles/Canonical/400-Enforce-inclusive-terms.yml
- styles/Canonical/500-Repeated-words.yml
Some issue with Vale means that `summary` scope is no longer working. `sentence` and `list` scopes combined should address most of the relevant cases for now.
> fix: use sentence + list scope over summary

- styles/config/vocabularies/Canonical/accept.txt
Update `accept.txt` to remove "juju" from the list of acceptable Canonical spellings.
Rule [004-Canonical-product-names](https://github.com/canonical/praecepta/blob/main/styles/Canonical/004-Canonical-product-names.yml) currently does not pick up on instances where "juju" appears in the text. "juju" (un-capitalized and not code-formatted) should not be included in the list of acceptable spellings.
To refer to Juju in text:
* When discussing the application manager, Juju should be capitalized.
* When discussing the CLI, `juju` should be code-formatted, so the style checker shouldn't get involved. The CLI shouldn't be referred to with "juju" (un-capitalized and not code-formatted).
> Remove lowercase juju from accept.txt

- README.md
- adding-dictionary-terms.md
- getting-started.md
- styles/config/dictionaries/en_US.dic
* Adds a tutorial for how to add terms to the dictionary
* Updates internal repo references 
* "Rebasing" to be added to dictionary.
`/A` is "re-"
`/G` is "-ing" (already exists)
Current term is: base/CDRSLTG
`/C` is "de-"
`/D` is "-d"
`/R` is "-r"
`/S` is "-s"
`/L` is "-ment"
`/T` is "-st"
`/G` is "-ing"
Adding `/A` would be incompatible ("rebaser(?)", "rebasement", "rebasest")
Instead we add `rebase/DSG`, for "rebased", "rebases", "rebasing".
> docs: add documentation for adding terms

- styles/config/vocabularies/Canonical/accept.txt
There was a mismatch between "Influxdb" in the accept.txt file,
and "InfluxDB" styles/Canonical/005-Industry-product-names.yml file.
> fix InfluxDB casing in vocabulary

- styles/config/vocabularies/Canonical/accept.txt
To prevent vale fail check because allowlist is not accepted.
allowlist (formerly known as a whitelist) is a security mechanism that explicitly defines a set of entities (e.g., IP addresses, domains, users, or applications) that are permitted to access or perform actions within the cluster, while implicitly denying access to all others.
> docs: add allowlist as accepted word
